function DDpsT_DDpsF = DDpsT_DDpsF
%DDPST_DDPSF
%    DDPST_DDPSF = DDPST_DDPSF

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:44:50

DDpsT_DDpsF = 0.0;
