function DDthT_DDthF = DDthT_DDthF
%DDTHT_DDTHF
%    DDTHT_DDTHF = DDTHT_DDTHF

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:44:50

DDthT_DDthF = 0.0;
