function Aij = A11(M,m1F,m2F,m1T,m2T,mcw)
%A11
%    AIJ = A11(M,M1F,M2F,M1T,M2T,MCW)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:43:55

Aij = M+m1F+m2F+m1T+m2T+mcw;
