function Aij = A17(mcw,rcw,thetaD)
%A17
%    AIJ = A17(MCW,RCW,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:43:57

Aij = -mcw.*rcw.*sin(thetaD);
