function Aij = A27(mcw,rcw,thetaD)
%A27
%    AIJ = A27(MCW,RCW,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:43:59

Aij = mcw.*rcw.*cos(thetaD);
