function Aij = A71(mcw,rcw,thetaD)
%A71
%    AIJ = A71(MCW,RCW,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:44:08

Aij = -mcw.*rcw.*sin(thetaD);
