function Aij = A72(mcw,rcw,thetaD)
%A72
%    AIJ = A72(MCW,RCW,THETAD)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:44:08

Aij = mcw.*rcw.*cos(thetaD);
