function Bi = B7(alfaA,g,mcw,rcw,thetaD,thetaD_d,xH_d,yH_d)
%B7
%    BI = B7(ALFAA,G,MCW,RCW,THETAD,THETAD_D,XH_D,YH_D)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    02-Dec-2022 15:44:32

t2 = cos(thetaD);
t3 = sin(thetaD);
t4 = rcw.*t2.*thetaD_d;
t5 = rcw.*t3.*thetaD_d;
t6 = -t5;
t7 = t4+yH_d;
t8 = t6+xH_d;
Bi = mcw.*(t5.*t7.*2.0-t4.*(t5-xH_d).*2.0).*(-1.0./2.0)+(mcw.*thetaD_d.*(rcw.*t3.*t7.*2.0-rcw.*t2.*(t5-xH_d).*2.0))./2.0-g.*mcw.*(rcw.*t2.*cos(alfaA)-rcw.*t3.*sin(alfaA));
